### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by browner12** [jamesadevine/sportsfont#1]
could you add this package to bower.io so we can install it with a dependency management tool, rather than just downloading the source?

**Comment by jamesadevine** [comment]
Hi, yeah I'll add that in later, do you have a recommended directory for installation? (new to creating a bower package - so i may be barking up the wrong tree)

**Comment by browner12** [comment]
i've actually never created a bower package, i only use them currently.

first off, though, you'll want to tag a release (probably version 1.0.0). if you're not familiar with [semantic versioning](http://semver.org/), i would look into it to learn how you should increment your versions.

then i would suggest just going to the [fontawesome repo](https://github.com/FortAwesome/Font-Awesome) and copying everything relating to bower exactly how Dave does it.

bower provides a [walk-through](http://bower.io/docs/creating-packages/) as well that should help

**Comment by jamesadevine** [comment]
Thanks for the help there - sportsfont can now be installed using bower:

`bower install sportsfont`

**Comment by browner12** [comment]
awesome man! good work!
